const level1 = new Level([
    new Chicken(350),
    new smallChicken(450),
    new Chicken(600),
    new smallChicken(800),
    new Chicken(900),
    new smallChicken(1000),
    new smallChicken(1100),
    new Chicken(1180),
    new smallChicken(1400),
    new smallChicken(1450),
    new smallChicken(1500),
    new Chicken(1600),
    new smallChicken(1700),
    new smallChicken(1800),
    new Chicken(1850),
    new Chicken(1880),
    new smallChicken(1900),
    new smallChicken(1930),
    new Endboss(1950)
],

[
    new Clouds(),
    new Clouds(),
    new Clouds(),
],
[
    new BackgroundObject('image/5_background/layers/air.png', -719),
    new BackgroundObject('image/5_background/layers/3_third_layer/1.png', -719),
    new BackgroundObject('image/5_background/layers/2_second_layer/1.png', -719),
    new BackgroundObject('image/5_background/layers/1_first_layer/1.png', -719),

    new BackgroundObject('image/5_background/layers/air.png', 0),
    new BackgroundObject('image/5_background/layers/3_third_layer/2.png', 0),
    new BackgroundObject('image/5_background/layers/2_second_layer/2.png', 0),
    new BackgroundObject('image/5_background/layers/1_first_layer/2.png', 0),

    new BackgroundObject('image/5_background/layers/air.png', 719),
    new BackgroundObject('image/5_background/layers/3_third_layer/1.png', 719),
    new BackgroundObject('image/5_background/layers/2_second_layer/1.png', 719),
    new BackgroundObject('image/5_background/layers/1_first_layer/1.png', 719),

    new BackgroundObject('image/5_background/layers/air.png', 719*2),
    new BackgroundObject('image/5_background/layers/3_third_layer/2.png', 719*2),
    new BackgroundObject('image/5_background/layers/2_second_layer/2.png', 719*2),
    new BackgroundObject('image/5_background/layers/1_first_layer/2.png', 719*2),
  
    new BackgroundObject('image/5_background/layers/air.png', 719*3),
    new BackgroundObject('image/5_background/layers/3_third_layer/1.png', 719*3),
    new BackgroundObject('image/5_background/layers/2_second_layer/1.png', 719*3),
    new BackgroundObject('image/5_background/layers/1_first_layer/1.png', 719*3),
], 
[
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins()
],
 [
        new Bottles(300, 380),
        new Bottles(400, 380),
        new Bottles(450, 380),
        new Bottles(600, 380),
        new Bottles(680, 380),
        new Bottles(750, 380),
        new Bottles(1000, 380),
        new Bottles(1200, 380),
        new Bottles(1350, 380),
        new Bottles(1500, 380),
        new Bottles(1700, 380),
    ]
)